apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: movie-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PAAS-data/movie_app.git
    targetRevision: main
    path: my-app/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true